# Linux Build Configuration for Travis

language: cpp

os:
  - linux

# Use Ubuntu 14.04 LTS (Trusty) as the Linux testing environment.
dist: trusty

env:
  # Each line is a set of environment variables set before a build.
  # Thus each line represents a different build configuration.
  - BUILD_TYPE=Release
  - BUILD_TYPE=Debug

compiler:
  - gcc
  - clang

script:
  - mkdir build && cd build
  - cmake -G "Unix Makefiles" -D CMAKE_BUILD_TYPE:STRING=${BUILD_TYPE}  ..
  - echo building in `nproc` processes 
  - make common_clang -j `nproc`

